parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: 'module'

extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'

plugins:
  - 'react-hooks'

rules:
  prettier/prettier:
    - error
    - trailingComma: none
      singleQuote: true
      semi: false
      tabWidth: 4
      jsxBracketSameLine: true
  '@typescript-eslint/explicit-function-return-type': 
    - off
  '@typescript-eslint/member-delimiter-style':
    - off
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: 'none'